name: Lint

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  nginx:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the source code
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: "3.11"

      - name: Generate a certficate to silence errors
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/files/certs
          openssl req -new -newkey rsa:4096 -x509 -days 365 -keyout ${GITHUB_WORKSPACE}/files/certs/default.key -out ${GITHUB_WORKSPACE}/files/certs/default.crt -nodes -subj "/CN=localhost"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install Gixy
        run: pip install gixy-ng

      - name: Run Gixy
        run: gixy files/nginx.conf

      - name: Check the Nginx configuration
        run: |
          sudo rm -rf /etc/nginx
          sudo cp -R "${GITHUB_WORKSPACE}/files" /etc/nginx/
          sudo nginx -t

  ansible:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the source code
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: "3.11"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install ansible ansible-lint yamllint

      - name: Lint Ansible
        run: ansible-lint .

      - name: Lint YAML
        run: yamllint .
