name: Lint

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  nginx:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the source code
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: "3.11"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install nginx-lint
        run: pip install nginx-lint

      - name: Run nginx-lint
        run: nginx-lint files/**/*.conf files/**/*.types

      - name: Check the Nginx configuration
        run: sudo nginx -t -c files/nginx.conf
        shell: bash
        env:
          NGINX_CONF_DIR: files
